### ISSUE TITLE
biobloomcategorizer: invalid option -- 'a'

### ISSUE THREAD

**Issue by mcmero** [bcgsc/pavfinder#1]
I am trying to run tap2 using a bloom filter like so:

`tap2.py sample . --bf ../../biobloomtools-2.3.2/test/reads.bf --fq sample_R1.fastq.gz sample_R2.fastq.gz --k 79 49 --readlen 101  --nprocs 1 --params params.ini`

However, I'm getting the following exception: 

```
Original exception:

    Exception #1
      'exceptions.Exception(Failed to run '/bin/bash -c "biobloomcategorizer --fq -i -p ./bbt_2.3.2/sample -a 2 -t 1 -e -f ../../biobloomtools-2.3.2/test/reads.bf sample_R1.fastq.gz sample_R2.fastq.gz"'
    biobloomcategorizer: invalid option -- 'a'
    Usage of paired end mode:
    BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [FILEPAIR1] [FILEPAIR2]
    or BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [SMARTPAIR]

    Non-zero exit status 1)' raised in ...
       Task = def classify(...):
       Job  = [[[sample_R1.fastq.gz], [sample_R2.fastq.gz]] -> bbt_2.3.2/sample_reads.fq, bbt_2.3.2/sample, .../test/reads.bf, 1]

    Traceback (most recent call last):
      File "/group/bioi1/marekc/apps/conda2/lib/python2.7/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/group/bioi1/marekc/apps/conda2/lib/python2.7/site-packages/ruffus/task.py", line 544, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/home/marek.cmero/.local/lib/python2.7/site-packages/pavfinder-1.4.0-py2.7.egg/EGG-INFO/scripts/tap2.py", line 223, in classify
        run_cmd('/bin/bash -c "%s"' % cmd)
      File "/home/marek.cmero/.local/lib/python2.7/site-packages/pavfinder-1.4.0-py2.7.egg/EGG-INFO/scripts/tap2.py", line 31, in run_cmd
        (cmd, stdout_str, stderr_str, process.returncode))
    Exception: Failed to run '/bin/bash -c "biobloomcategorizer --fq -i -p ./bbt_2.3.2/sample -a 2 -t 1 -e -f ../../biobloomtools-2.3.2/test/reads.bf sample_R1.fastq.gz sample_R2.fastq.gz"'
    biobloomcategorizer: invalid option -- 'a'
    Usage of paired end mode:
    BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [FILEPAIR1] [FILEPAIR2]
    or BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [SMARTPAIR]

    Non-zero exit status 1
```

Looking into biobloomcategorizer, the latest version does not appear to have the `-a` option. Which version(s) of biobloomcategorizer are compatible with tap?

**Comment by sjackman** [comment]
cc @JustinChu

**Comment by JustinChu** [comment]
I think this is version mismatch issue. The `-a` option was removed a few versions back and moved to `biobloommicategorizer`

**Comment by sjackman** [comment]
@readmanchiu Can `pavfinder` be updated to use the most recent version of BioBloomTools?

@JustinChu If it's possible could the `-a` option be added back to `biobloomcategorizer` for compatibility with Pavfinder?

**Comment by JustinChu** [comment]
It wouldn't be advisable to do so, since all miBF functionality would have to be added back to the executable and it was seperated to avoid confusion between the tools.

**Comment by sjackman** [comment]
@readmanchiu Sounds like `pavfinder` should use `biobloommicategorizer` rather than `biobloomcategorizer`.

**Comment by readmanchiu** [comment]
sorry about that, there has been some issues of making the changes to use the latest version of BBT, I will work on that again. The current version of BBT that TAP is compatible with is 2.1.0.

**Comment by readmanchiu** [comment]
@mcmero I changed tap2 to be compatible with bbt v2.3.3, and now it uses biobloommicategorizer instead of biobloomcategorizer. Just a caveat you may have to adjust the -b parameter when you used biobloommimaker to create your filter (you may have to lower -b if you have fewer than 100 targets). Please consult @JustinChu in this regard. From our end, I'll do more testing to understand the behavior of this new BBT before I tag the release.
