### ISSUE TITLE
FusionBloom - some cases generate error in minimap2 | samtools command

### ISSUE THREAD

**Issue by af8** [bcgsc/pavfinder#12]
I have run fusionbloom Makefile on many samples and sometimes I have hit the following problem :

```
[M::mm_idx_gen::65.134*1.72] collected minimizers
[M::mm_idx_gen::67.565*2.59] sorted minimizers
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::67.565*2.59] loaded/built the index for 1840298 target sequence(s)
[M::mm_mapopt_update::67.565*2.59] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1840298
[M::mm_idx_stat::69.322*2.55] distinct minimizers: 143473236 (47.28% are singletons); average occurrences: 4.613; average spacing: 6.044
[E::sam_parse1] no SQ lines present in the header
[W::sam_read1] Parse error at line 2
samtools view: error reading file "-"
```

minimap2 raises a warning claiming that no @SQ lines will be generated in output sam file. The consequence is that `samtools view` then fails because of these missing header lines.

A simple fix is to add the `-t` option to the `samtools view` command, filling it with the `$sample.transcripts.filtered.fa.fai` created before.

```
minimap2 -ax sr -t 32 ./rnabloom/sample.transcripts.filtered.fa sample_R1.fastq.gz sample_R2.fastq.gz | \
samtools view -uhS -t ./rnabloom/sample.transcripts.filtered.fa.fai - | \
samtools sort -m 20G - -o ./r2c.bam
```

With this option set the command completes.

Anthony

**Comment by readmanchiu** [comment]
Thanks @af8 for reporting the issue, will run some tests on the suggested solution and incorporate the change if things look ok

**Comment by readmanchiu** [comment]
`-t $(assembly_outdir)/$(name).transcripts.filtered.fa.fai` has been tested and incorporated into the `samtools` command of the `r2c` step
I haven't tested on a large dataset with the issue, but I have definitely seen this issue with minimap2 before. Thanks 
@af8 for suggesting this simple solution.

**Comment by af8** [comment]
OK thanks I close this issue.
