### ISSUE TITLE
Error running tap2.py on example data: input file does not exist

### ISSUE THREAD

**Issue by rhalperin** [bcgsc/pavfinder#17]
I am trying to run tap2.py on the data in [pavfinder/test/transcriptome](https://github.com/bcgsc/pavfinder/tree/master/pavfinder/test/transcriptome).  I am using the following command:
```
tap2.py test /results/pavfinder/test/tap --bf test_genes.bf --fq test_1.fastq.gz test_2.fastq.gz --k 32 62 92 --readlen 100 --params test.cfg --remove_fq >pavfinder_test_tap.out 2>pavfinder_test_tap.err
```
I get the error:
```
No way to run job: Input file '/results/pavfinder/test/tap/rnabloom_1.4.3/ATXN3/ATXN3.transcripts.fa' does not exist
```
Here are my log file, stdout, and stderr:
[log.2022-04-15_15_02_19.txt](https://github.com/bcgsc/pavfinder/files/8496669/log.2022-04-15_15_02_19.txt)
[pavfinder_test_tap.err.txt](https://github.com/bcgsc/pavfinder/files/8496680/pavfinder_test_tap.err.txt)
[pavfinder_test_tap.out.txt](https://github.com/bcgsc/pavfinder/files/8496681/pavfinder_test_tap.out.txt)

Here is what my output directory looks like:
```
tree /results/pavfinder/test/tap/
/results/pavfinder/test/tap/
├── bbt_2.3.3
│   ├── ATXN3_1.fastq
│   ├── ATXN3_2.fastq
│   ├── CEBPA_1.fastq
│   ├── CEBPA_2.fastq
│   ├── FLT3_1.fastq
│   ├── FLT3_2.fastq
│   ├── FOXP1_1.fastq
│   ├── FOXP1_2.fastq
│   ├── KMT2A_1.fastq
│   ├── KMT2A_2.fastq
│   ├── NPM1_1.fastq
│   ├── NPM1_2.fastq
│   ├── NSD1_1.fastq
│   ├── NSD1_2.fastq
│   ├── NUP98_1.fastq
│   ├── NUP98_2.fastq
│   ├── test_reads.fq
│   └── test_summary.tsv
├── logs
│   ├── log.2022-04-15_14:57:16.txt
│   ├── log.2022-04-15_14:57:22.txt
│   └── log.2022-04-15_15:02:19.txt
├── pv_1.8.0
└── rnabloom_1.4.3
    ├── ATXN3
    ├── CEBPA
    ├── FLT3
    ├── FOXP1
    ├── KMT2A
    ├── NPM1
    ├── NSD1
    └── NUP98

12 directories, 21 files
```

**Comment by kmnip** [comment]
It looks like the run failed at the assembly stage.
Do you have RNA-Bloom installed?
```
conda install -c bioconda rnabloom
```

**Comment by rhalperin** [comment]
Yes (though I didn't install via conda, I just downloaded the latest release)
```
rnabloom --version
RNA-Bloom v1.4.3
Ka Ming Nip, Canada's Michael Smith Genome Sciences Centre, BC Cancer
Copyright 2018-present
```

**Comment by rhalperin** [comment]
I figured out that I was missing an RNA-Bloom dependency.  I fixed that and it works now.
