### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by kmnip** [bcgsc/pavfinder#20]
I think we can add a conda recipe for installing PAVFinder as all required software packages are on bioconda now. The readme page can then be updated to include the installation command. In fact, the readme page doesn't have any installation info.

BioBloomTools, RNA-Bloom, and Trans-ABySS are depended by PAVFinder for the FusionBloom and TAP workflows. So, these dependencies need to be updated in the `requirements.txt`.

**Comment by readmanchiu** [comment]
Thanks @kmnip will give this a shot!

**Comment by kmnip** [comment]
Hi Readman, I would like to take on this task. Here is my plan.

1. create a `conda` environment that works for the different pipelines:
   - TAP
   - TAP2
   - FusionBloom
3. run through each pipeline using small datasets
4. confirm the results are reasonable
5. update the requirements if necessary, and add instructions for conda environment in README
6. make a new recipe in bioconda

How does that sound?

**Comment by readmanchiu** [comment]
Thanks Ka Ming for taking this on! Before packaging the pipelines, we do have to package PAVFinder on its own first, don't we? I can help with the testing.
And we will have separate recipes for each pipeline, right?

**Comment by kmnip** [comment]
No, we don't need to repackage anything as long as we can create a single conda environment that works for all 3 pipelines. This is the part that I am trying to figure out. Once we are comfortable with the results, building the recipe should be straightforward following that.

**Comment by kmnip** [comment]
Having an issue in my PR for the bioconda recipe:
https://github.com/bioconda/bioconda-recipes/pull/37231

**Comment by readmanchiu** [comment]
The only thing I see is in the `setup.py`, I forgot to include `pavfinder/test/transcriptome/expected_output/tap2.tar.gz` in `data_files`.
But I don't see anywhere in your recipe you asked to run `setup.py` or how it could affect the build. Even if I ran `pip` to install, which uses `setup.py`, it won't notice.

**Comment by kmnip** [comment]
The recipe can be made as a pure python package, which uses purely `pip` during the build. I was actually trying this method previously and it worked fine for all Python/bash scripts except for `fusion-bloom`, which is a `make` file.

So, the build script now creates a bash script that runs a `make -f` command, which points to the `fusion-bloom` `make` file. Then, it runs the `pip` command. The build process ran fine until it reaches some point that fails with a "filenotfound" error for `fusion-bloom`. I am a bit clueless about this.

I think the solution to bypass this issue is to make the following changes within our repo.

1. Rename `fusion-bloom` as `fusion-bloom.makefile`
2. Create a bash script, similar to `filer_fasta`, i.e.
```
#!/bin/bash

script_dir=`dirname $0`
make -f $script_dir/fusion-bloom.makefile $@
```
3. Add this script in `setup.py`.
So, both `fusion-bloom` (now as a bash script) and `fusion-bloom.makefile` will be installed. The bioconda recipe can simply use `fusion-bloom`.

**Comment by readmanchiu** [comment]
But we still don't know what causes the "missing file" problem?

**Comment by kmnip** [comment]
No, and I have already ping the maintainers about this. I actually test the script with a `cat` command and I can see the contents of the script in the log. It only fails later in the build process.

I don't have this issue at all when the recipe only builds with `pip` without my custom build bash script. That's why I am suggesting that we make the changes within our repo.

**Comment by readmanchiu** [comment]
if you want to make the change, let's go ahead and do it

**Comment by kmnip** [comment]
My PR in bioconda-recipes has been merged. I will test the bioconda package now.

**Comment by kmnip** [comment]
Test installation was successful:
```
conda create -n pavfinder
conda activate pavfinder
mamba install -c bioconda pavfinder
which tap tap2 fusion-bloom
```

**Comment by kmnip** [comment]
Test runs were successful for `fusion-bloom`, `tap`, and `tap2` from the bioconda package.
