### ISSUE TITLE
how are "dup" vs "ITD" defined by pavfinder

### ISSUE THREAD

**Issue by rhalperin** [bcgsc/pavfinder#21]
Could you please describe what criteria pavfinder uses to categorize an event as a "dup" vs "ITD".  Thanks!

**Comment by readmanchiu** [comment]
Duplications ("dup") are classified as "ITD" where one or both of the breakpoint boundaries are within coding exons. Unfortunately for your case in the other ticket where the event could only be captured by c2t alignment, the FLT3 transcript chosen for generating the reference transcripts (`--transcripts_fasta`) is a non-coding one. If it had been a coding transcript, the event would have been labelled "ITD" as it should be.
