### ISSUE TITLE
Example output files?

### ISSUE THREAD

**Issue by stianlagstad** [bcgsc/pavfinder#6]
Hi,

I would like to know if the output data that Fusion-Bloom produces can be used with https://github.com/stianlagstad/chimeraviz. Do you have any example output files that you can share?

Thank you!

**Comment by readmanchiu** [comment]
Thanks for your interest in Fusion-Bloom and sorry for the late reply. There is a compressed file of Fusion-Bloom output in the test directory: 
https://github.com/bcgsc/pavfinder/blob/master/pavfinder/test/transcriptome/expected_output/fusion-bloom.out.tar.gz
After decompressing and extracting (`tar xzvf`), you can find the fusion output under the `pavfinder` folder. And as the name(`sv.bedpe`) suggests, it is a BEDPE format file, with the first three lines describing the version, command, and columns respectively. I don't think any of the fusion tools you supported uses the BEDPE format, but all the information should be in the output for you to, for example, generate a circos plot.
Let me know if you need any more information, and I'm happy to write a parser for you if necessary.

**Comment by stianlagstad** [comment]
Thank you very much @readmanchiu ! I don't have time to look at it the first coming days, but I'll get to it :) I've created https://github.com/stianlagstad/chimeraviz/issues/85 on my end to track it.
