### ISSUE TITLE
filter_fasta script generates erroneous "transcripts.filtered.fa"

### ISSUE THREAD

**Issue by af8** [bcgsc/pavfinder#8]
Hi,

`filter_fasta` in fusion-bloom Makefile generates a fasta with some fasta headers being duplicated (but not the fasta sequence).

I have replaced the `$(assembly_outdir)/$(name).transcript.filtered.fa` target with :

```
# filter contigs with minimum length(Q1)
$(assembly_outdir)/$(name).transcripts.filtered.fa: $(assembly_outdir)/$(name).transcripts.nr.fa
	$(eval L := $(shell grep Q1 $(assembly_outdir)/$(name).fragstats | cut -f2 -d':'))
	@echo $(L)
	awk -v min=$(L) 'BEGIN {RS = ">" ; ORS = ""} length($$2) >= min {print ">"$$0}' $(assembly_outdir)/$(name).transcripts.nr.fa > $(assembly_outdir)/$(name).transcripts.filtered.fa && \
	samtools faidx $(assembly_outdir)/$(name).transcripts.filtered.fa
```
and it works fine.

I have borrowed the code snippet from [here](https://www.biostars.org/p/79202/). Alternatively, you can put this awk snippet in a script.

EDIT: I have added a erroneous `filtered.fa` example.
[test.transcripts.filtered.fa.log](https://github.com/bcgsc/pavfinder/files/4411088/test.transcripts.filtered.fa.log)

Best,
Anthony

**Comment by readmanchiu** [comment]
Thanks Anthony, I have written a simple custom script to handle this and `filter_fasta` becomes a wrapper for it.
Sorry for the late response.
